trigger: none

variables:
  imageName: knightfortheright
  imageTag: $(Build.BuildId)
  fullImageName: $(imageName):$(imageTag)

pool:
  vmImage: 'ubuntu-latest'

steps:
# 1. Checkout your source code
- checkout: self
  fetchDepth: 0

# 2. Build Docker image locally
- script: |
    echo "Building Docker image locally: $(fullImageName)"
    docker build -t $(fullImageName) .
  displayName: "Build Docker Image"

# 3. Scan with Aqua Trivy (Aqua scanner container)
- script: |
    echo "Scanning local Docker image with Aqua Trivy..."
    docker run --rm \
      -e AQUA_KEY=$(AQUA_KEY) \
      -e AQUA_SECRET=$(AQUA_SECRET) \
      -e AQUA_URL=https://api.eu-1.supply-chain.cloud.aquasec.com \
      -e CSPM_URL=https://eu-1.api.cloudsploit.com \
      -e TRIVY_RUN_AS_PLUGIN=aqua \
      -v /var/run/docker.sock:/var/run/docker.sock \
      aquasec/aqua-scanner \
      trivy image --scanners vuln,misconfig,secret $(fullImageName)
  displayName: "Scan Image with Aqua"
  env:
    AQUA_KEY: $(AQUA_KEY)
    AQUA_SECRET: $(AQUA_SECRET)

# 4. Install and run Billy to generate SBOM locally
- script: |
    echo "Installing Billy for SBOM generation..."
    curl -sLo install.sh https://download.codesec.aquasec.com/billy/install.sh
    curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum

    sha256sum -c install.sh.checksum || { echo "Checksum validation failed"; exit 1; }

    BINDIR="." sh install.sh
    rm install.sh install.sh.checksum

    echo "Generating SBOM from local Docker image..."
    ./billy generate \
      --access-token $(System.AccessToken) \
      --aqua-key $(AQUA_KEY) \
      --aqua-secret $(AQUA_SECRET) \
      --cspm-url https://eu-1.api.cloudsploit.com \
      --artifact-path $(fullImageName)
  displayName: "Generate SBOM with Billy"
