trigger: none

variables:
  imageName: knightfortheright/mytest
  imageTag: $(Build.BuildId)
  fullImageName: $(imageName):$(imageTag)

pool:
  vmImage: 'ubuntu-latest'

steps:
# 1. Checkout the code
- checkout: self
  fetchDepth: 0

# 2. Docker login (if pulling base image or pushing to registry)
- script: |
    echo "$(DOCKER_PASSWORD)" | docker login -u "$(DOCKER_USERNAME)" --password-stdin
  displayName: "Docker Login"
  env:
    DOCKER_USERNAME: $(DOCKER_USERNAME)
    DOCKER_PASSWORD: $(DOCKER_PASSWORD)

# 3. Build Docker image
- script: |
    echo "Building Docker image: $(fullImageName)"
    docker build -t $(fullImageName) .
  displayName: "Build Docker Image"

# 4. Scan with Aqua Trivy
- script: |
    echo "Running Aqua Trivy scan..."
    docker run --rm \
      -e AQUA_KEY=$(AQUA_KEY) \
      -e AQUA_SECRET=$(AQUA_SECRET) \
      -e AQUA_URL=https://api.eu-1.supply-chain.cloud.aquasec.com \
      -e CSPM_URL=https://eu-1.api.cloudsploit.com \
      -e TRIVY_RUN_AS_PLUGIN=aqua \
      -v /var/run/docker.sock:/var/run/docker.sock \
      aquasec/aqua-scanner \
      trivy image --scanners vuln,misconfig,secret $(fullImageName)
  displayName: "Scan Image with Aqua"
  env:
    AQUA_KEY: $(AQUA_KEY)
    AQUA_SECRET: $(AQUA_SECRET)

# 5. Install & run Billy to generate SBOM
- script: |
    echo "Installing Billy for SBOM..."
    curl -sLo install.sh https://download.codesec.aquasec.com/billy/install.sh
    curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum

    sha256sum -c install.sh.checksum || { echo "Checksum validation failed"; exit 1; }

    BINDIR="." sh install.sh
    rm install.sh install.sh.checksum

    echo "Generating SBOM..."
    ./billy generate \
      --access-token $(System.AccessToken) \
      --aqua-key $(AQUA_KEY) \
      --aqua-secret $(AQUA_SECRET) \
      --cspm-url https://eu-1.api.cloudsploit.com \
      --artifact-path $(fullImageName)
  displayName: "Generate SBOM with Billy"
