trigger: none

container:
  image: aquasec/aqua-scanner
  env:
    AQUA_KEY: $(AQUA_KEY)
    AQUA_SECRET: $(AQUA_SECRET)
    AZURE_TOKEN: $(AZURE_TOKEN)
    AQUA_URL: https://api.eu-1.supply-chain.cloud.aquasec.com
    CSPM_URL: https://eu-1.api.cloudsploit.com
    TRIVY_RUN_AS_PLUGIN: aqua

steps:
# 1. Checkout your code
- checkout: self
  fetchDepth: 0

# 2. Run Aqua filesystem scan
- script: |
    echo "Running Aqua scanner on source code..."
    trivy fs --scanners misconfig,vuln,secret .
  displayName: "Aqua Scanner - Source Code"

# 3. Install and run Billy for SBOM generation (filesystem mode)
- script: |
    echo "Installing Billy for SBOM generation..."
    curl -sLo install.sh https://download.codesec.aquasec.com/billy/install.sh
    curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum

    sha256sum -c install.sh.checksum || { echo "Checksum validation failed"; exit 1; }

    BINDIR="." sh install.sh
    rm install.sh install.sh.checksum

    echo "Generating SBOM from source folder..."
    ./billy generate \
      --access-token $(System.AccessToken) \
      --aqua-key $(AQUA_KEY) \
      --aqua-secret $(AQUA_SECRET) \
      --cspm-url https://eu-1.api.cloudsploit.com \
      --artifact-path .
  displayName: "Generate SBOM with Billy (Source Code)"
