trigger: none

variables:
  versionEnv: $(Build.BuildId)

jobs:
- job: AquaScan
  displayName: "Aqua Vulnerability Scan"
  container:
    image: aquasec/aqua-scanner
    env:
      AQUA_KEY: $(AQUA_KEY)
      AQUA_SECRET: $(AQUA_SECRET)
      AZURE_TOKEN: $(AZURE_TOKEN)
      AQUA_URL: https://api.eu-1.supply-chain.cloud.aquasec.com
      CSPM_URL: https://eu-1.api.cloudsploit.com
      TRIVY_RUN_AS_PLUGIN: aqua

  steps:
    - checkout: self
      fetchDepth: 0

    - script: |
        trivy fs --scanners misconfig,vuln,secret . \
        --severity UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
      displayName: "Run Aqua Scanner"

- job: SBOMGen
  displayName: "SBOM Generation with Billy"
  pool:
    vmImage: 'ubuntu-latest'

  variables:
    versionEnv: $(Build.BuildId)

  steps:
    - checkout: self

    - script: |
        echo "Installing Billy for SBOM generation..."
        export BILLY_SERVER=https://billy.eu-1.codesec.aquasec.com

        curl -sLo install.sh https://download.codesec.aquasec.com/billy/install.sh
        curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum

        sha256sum -c install.sh.checksum || { echo "Checksum validation failed"; exit 1; }

        BINDIR="." sh install.sh
        rm install.sh install.sh.checksum

        echo "Generating SBOM..."
        ./billy generate \
          --access-token $(System.AccessToken) \
          --aqua-key $(AQUA_KEY) \
          --aqua-secret $(AQUA_SECRET) \
          --cspm-url https://eu-1.api.cloudsploit.com \
          --artifact-path "your-image-name:$(versionEnv)"
      displayName: "Install & Run Billy"

      displayName: "Install & Run Billy"
